[package]
name = "poker-game-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix = "0.12"
actix-web-actors = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8"